---
- name: Create temp directory for github-release-downloader
  file: path={{ sanity_check_temporary_download_dir }} state=directory mode=0775 owner=insight group=insight

- name: Download github release downloader
  unarchive: src="https://github.com/palette-software/dl-github-release/releases/download/v1.0.2/linux_amd64.zip" dest={{ sanity_check_temporary_download_dir }} copy=no
  become_user: insight

- name: Download insight-tester with github release downloader
  shell: '{{ sanity_check_temporary_download_dir }}/linux_amd64/dl-github-release palette-software insight-tester {{ github_token }}'
  become_user: insight
  args:
    chdir: '{{ sanity_check_temporary_download_dir }}/linux_amd64'
  no_log: True

- name: Unpack insight-tester to acquire dbcheck (sanity checker)
  unarchive: src={{ sanity_check_temporary_download_dir }}/linux_amd64/linux_amd64.zip dest={{ sanity_check_temporary_download_dir }} copy=no
  become_user: insight

- name: Delete previous sanity checker installations
  file: path='{{ sanity_check_install_dir }}' state=absent
  become_user: root

- name: Create directory for sanity checker
  file: path='{{ sanity_check_install_dir }}' state=directory mode=0775 owner=insight group=insight
  become_user: root

- name: Place sanity checker into its final destination (overwrite earlier contents)
  shell: 'mv -f {{ sanity_check_temporary_download_dir }}/linux_amd64/sanity_check/* {{ sanity_check_install_dir }}'
  become_user: insight

- name: Delete temporary folders
  file: path='{{ sanity_check_temporary_download_dir }}' state=absent

- name: Make sanity check configuration
  template: src=Config.yml dest={{ sanity_check_install_dir }}/Config.yml owner=insight group=insight

- name: Make sanity check runner script for cron
  template: src=roles/sanity-check/templates/sanity-check.sh dest={{ sanity_check_install_dir }}/sanity-check.sh owner=insight group=insight mode=0744
