sshKey = File.read("keys/insight-deploy-key.pub")

nodes = [
  { :hostname => 'insight-control',   :ip => '192.168.1.40', :box => 'palette-insight-centos67', :provision => ["scripts/control-provision.sh"] },
  { :hostname => 'insight-s1',      :ip => '192.168.1.50', :box => 'palette-insight-centos67' },
  #{ :hostname => 'insight-s2',      :ip => '192.168.0.51', :box => 'palette-insight-centos67' }
]

Vagrant.configure("2") do |config|
  nodes.each do |node|
    config.vm.define node[:hostname] do |nodeconfig|
      nodeconfig.vm.box = node[:box]
      nodeconfig.vm.hostname = node[:hostname] + ".box"
      nodeconfig.vm.network :private_network, ip: node[:ip]

      memory = node[:ram] ? node[:ram] : 256;
      nodeconfig.vm.provider :virtualbox do |vb|
        vb.customize [
          "modifyvm", :id,
          "--cpuexecutioncap", "50",
          "--memory", memory.to_s,
        ]
      end

      nodeconfig.vm.synced_folder "../", "/provisioning"
      nodeconfig.vm.provision "shell", inline: <<-EOF
        echo '#{sshKey}' >> /home/vagrant/.ssh/authorized_keys
      EOF

      if node[:provision]
        node[:provision].each do |provision|
            nodeconfig.vm.provision "shell", path: provision
        end
      end
    end
  end

end
