---
- name: Keep temporary old hostname in /etc/hosts
  lineinfile:
    dest=/etc/hosts
    regexp="^127\.0\.1\.1(.*)"
    line="127.0.1.1{{'\t'}}{% if hostname_name != hostname_fqdn %}{{ hostname_fqdn }}{{'\t'}}{% endif %}{{ hostname_name }}\1"
    state=present
    backup=yes
    backrefs=yes
  when: ansible_hostname != hostname_name

- name: Set hostname
  hostname: name={{ hostname_name }}
  when: hostname_name is defined

- name: Update /etc/hosts
  lineinfile:
    dest=/etc/hosts
    regexp="^127\.0\.1\.1"
    line="127.0.1.1{{'\t'}}{% if hostname_name != hostname_fqdn %}{{ hostname_fqdn }}{{'\t'}}{% endif %}{{ hostname_name }}"
    state=present
