---
- name: install ca package on rhel systems
  yum:
    name: ca-certificates
    state: present
  when: ansible_os_family == "RedHat"

- name: enable dynamic ca configuration on CentOS / RedHat 6
  shell: update-ca-trust force-enable

- include: "epel.yml"
- include: "ius.yml"

- name: Install SELinux bindings for ansible
  yum: name={{ item }} state=present
  with_items:
    - libsemanage-python
    - libselinux-python

- name: Copy the Palette repository definition
  copy: src=palette.repo dest=/etc/yum.repos.d/

- name: Install PIP
  package: name=python-pip state=present
