---
- name: Add centos group
  group: name=centos gid=999

- name: Add centos user
  user: name=centos uid=999 group=centos

- name: Add centos user to sudoers
  lineinfile: "dest=/etc/sudoers state=present regexp='^centos' line='centos ALL=(ALL) NOPASSWD: ALL'"

- name: update packages
  yum: name=* state=latest
  async: 3600 # 60 minutes max runtime allowed
  poll: 10

- name: install ca package on rhel systems
  yum:
    name: ca-certificates
    state: present
  when: ansible_os_family == "RedHat"

- name: enable dynamic ca configuration on CentOS / RedHat 6
  shell: update-ca-trust force-enable
  when: ansible_os_family == "RedHat"

- include: "epel.yml"
- include: "ius.yml"
- include: "insight-user.yml"

# Set up the hostnames
#
- name: Install SELinux bindings for ansible
  yum: name={{ item }} state=present
  with_items:
    - libsemanage-python
    - libselinux-python

- name: Disable SELinux
  selinux: state=disabled

- name: 'Set up the hostnames. NOTE: You have to use FQDNs in your inventory or assign the >>hostname_fqdn<< for each server.'
  include: "hostname.yml"

- name: Copy the Palette repository definition
  copy: src=palette.repo dest=/etc/yum.repos.d/

- name: Install PIP
  package: name=python-pip state=present

- name: Disable IpTables (should use EC2 Security Groups)
  service: name=iptables enabled=no state=stopped

- name: Sudo tabcompletion
  lineinfile: dest=/etc/profile regexp='^complete -cf sudo$' line='complete -cf sudo'

- name: Set the server timezone to UTC
  include: "utc_timezone.yml"

