---
- name: install ca package on rhel systems
  yum:
    name: ca-certificates
    state: present
    #disablerepo: epel
  when: ansible_os_family == "RedHat"

#- name: enable dynamic ca configuration on rhel6
  #shell: /bin/update-ca-trust enable
  #when: ansible_os_family == "RedHat"  and ansible_distribution_major_version|int == 6

- name: enable dynamic ca configuration on centos6
  shell: update-ca-trust force-enable
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version|int == 6

- include: "epel.yml"
- include: "ius.yml"

- name: Install SELinux bindings for ansible
  yum: name={{ item }} state=present
  with_items:
    - libsemanage-python
    - libselinux-python

- name: Copy the Palette repository definition
  copy: src=palette.repo dest=/etc/yum.repos.d/

- name: Install PIP
  package: name=python-pip state=present
