---
# Uncomment this, to copy a local repository to the server (and the
# reference line in the next task too). With that, the "git clone"
# doesn't need to fetch the whole repository from github. That saves
# some time if you're running everything locally and have a slow network
# connection.
#
#- name: Speed up the clone by setting up a local reference repo
#  synchronize: src=/home/heikki/gpdb-ansible-scripts/gpdb.git/ dest=/home/gpadmin/gpdb.git/

# Pass recursive=no to not fetch submodules
- name: Clone GPDB repository
  git:
    repo: "https://github.com/greenplum-db/gpdb.git"
    dest: /home/gpadmin/gpdb
    recursive: no
    version: "{{ branchname | default('master') }}"
    #reference: /home/gpadmin/gpdb.git
  become: yes
  become_user: gpadmin

- name: Configure
  command: ./configure --enable-debug --enable-depend --disable-gpfdist chdir=/home/gpadmin/gpdb creates=/home/gpadmin/gpdb/config.status
  become: yes
  become_user: gpadmin

- name: Compile
  command: make -j4 -s chdir=/home/gpadmin/gpdb
  become: yes
  become_user: gpadmin

- name: Add greenplum_path.sh to .bashrc
  lineinfile: dest=/home/gpadmin/.bashrc line=". /usr/local/gpdb/greenplum_path.sh"
  become: yes
  become_user: gpadmin

- name: Install greenplum
  command: make -s install chdir=/home/gpadmin/gpdb

- name: Chown binaries to root
  file:
    path: /usr/local/gpdb
    mode: 0755
    owner: root
    group: root
    recurse: yes


