---
- name: Create /data/primary
  file: path={{ item }} state=directory owner={{ greenplum_user }} group=root mode="u=rwx,g=rx,o=rx"
  with_items:
    - /data/primary
    - /data/master

- name: Create gphosts file
  template: src=gphosts dest={{ greenplum_hosts_file }} owner=root group=root mode="u=rw,g=r,o=r"

- name: Create gpinitsystem_singlenode file
  template: src=gpinitsystem_singlenode dest=/home/{{ greenplum_user }}/gpinitsystem_singlenode owner={{ greenplum_user }} group={{ greenplum_user }}

- name: Add MASTER_DATA_DIRECTORY to .bashrc
  lineinfile: dest=/home/{{ greenplum_user }}/.bashrc regexp="^export MASTER_DATA_DIRECTORY=" line="export MASTER_DATA_DIRECTORY={{ greenplum_datadir }}/master/gpsne-1"

- name: Exchange ssh keys using gpssh-exkeys & run gpinitsystem
  shell: bash -lc "{{ item }}"
  with_items:
    - gpssh-exkeys -f {{ greenplum_hosts_file }}
    - gpinitsystem -a -h {{ greenplum_hosts_file }} -c /home/{{ greenplum_user }}/gpinitsystem_singlenode

  become: yes
  become_user: "{{ greenplum_user }}"

#- name: Run gpinitsystem
  #command: gpinitsystem -a -h {{ greenplum_hosts_file }} -c /home/{{ greenplum_user }}/gpinitsystem_singlenode
  #ignore_errors: yes
  #become: yes
  #become_user: "{{ greenplum_user }}"


## gpinitsystem gets stuck while trying to connect to master, if
## master's host key isn't already in known_hosts.
#- name: Populate ssh known_hosts
  #command: ssh -o StrictHostKeyChecking=false gpdb-test-master true


- name: Allow remote logins
  lineinfile: dest={{ greenplum_datadir }}/master/gpsne-1/pg_hba.conf line="host all all 0.0.0.0/0 md5"
  #become: yes
  #become_user: "{{ greenplum_user }}"


- name: Reload config
  shell: bash -lc "pg_ctl -D {{ greenplum_datadir }}/master/gpsne-1 reload"
  become: yes
  become_user: "{{ greenplum_user }}"

#- name: Create Palette DB in GreenPlum
  #shell: createdb palette
  #become: yes
  #become_user: "{{ greenplum_user }}"
# gpseginstall -f {{ greenplum_hosts_file }} -u {{ greenplum_user }} -p Lofasz1234
#
#
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
# gpconfig -c statement_mem -v 1000MB
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
