---
- name: Install Greenplum from the greenplum-metal-{{ greenplum_version_rpm }} package
  yum: name=greenplum-metal-{{ greenplum_version_rpm }} state=present

- name: Update the install path in greenplum_path.sh
  lineinfile:
    dest: "{{ greenplum_install_dir }}/greenplum_path.sh"
    regexp: "^GPHOME=.*"
    line: "GPHOME={{greenplum_install_dir}}"

- name: Source the greenplum shell scripts in the {{ greenplum_user }} user bashrc
  lineinfile:
    dest: /home/{{ greenplum_user }}/.bashrc
    regexp: "^source .*greenplum_path.sh"
    line: "source {{ greenplum_install_dir }}/greenplum_path.sh"

