---

- name: Checking version of greenplum (target is {{ greenplum_version_target }})
  shell: bash -lc  "gpstate -b" | perl -l -ne '/postgres \(Greenplum Database\) (\d+\.\d+\.\d+\.\d+)/ && print $1'
  become: yes
  become_user: gpadmin
  ignore_errors: yes
  register: gp_version
  changed_when: false

- include: "{{ item }}"
  when: gp_version|failed or gp_version.stdout != greenplum_version_target
  with_items:
    - prepare-machine.yml
    - install.yml
