---
- name: Create {{ greenplum_user }} user
  user: name={{ greenplum_user }}

- name: Copy gpdb-limits.conf to raise ulimits
  copy: src=gpadmin-limits.conf dest=/etc/security/limits.d/99-{{ greenplum_user }}-limits.conf

- name: Install gcc (needed to install modules with pip)
  package: name=gcc state=present

- name: install packages needed to run GPDB
  yum: name=python-paramiko,python-pip,net-tools,python-devel

- name: install PIP packages needed to run GPDB
  pip: name={{ item }}
  with_items:
    - psi
    - lockfile

- name: Setup sysctl for GreenPlum
  sysctl: name={{ item.name }} value={{ item.value }} state=present sysctl_set=yes
  with_items:
    - { name: "kernel.shmmax", value: 500000000 }
    - { name: "kernel.shmmni", value: 4096 }
    - { name: "kernel.shmall", value: 4000000000 }
    - { name: "kernel.sem", value: 250 512000 100 2048 }
    - { name: "kernel.sysrq", value: 1 }
    - { name: "kernel.core_uses_pid", value: 1 }
    - { name: "kernel.msgmnb", value: 65536 }
    - { name: "kernel.msgmax", value: 65536 }
    - { name: "kernel.msgmni", value: 2048 }
    - { name: "net.ipv4.tcp_syncookies", value: 1 }
    - { name: "net.ipv4.ip_forward", value: 0 }
    - { name: "net.ipv4.conf.default.accept_source_route", value: 0 }
    - { name: "net.ipv4.tcp_tw_recycle", value: 1 }
    - { name: "net.ipv4.tcp_max_syn_backlog", value: 4096 }
    - { name: "net.ipv4.conf.all.arp_filter", value: 1 }
    - { name: "net.ipv4.ip_local_port_range", value: 1025 65535 }
    - { name: "net.core.netdev_max_backlog", value: 10000 }
    - { name: "net.core.rmem_max", value: 2097152 }
    - { name: "net.core.wmem_max", value: 2097152 }
    - { name: "vm.overcommit_memory", value: 2 }
    - { name: "vm.overcommit_ratio", value: 95 }

- name: Reload sysctl
  command: /sbin/sysctl -p

- name: Set disk device to have a read-ahead (blockdev) of 16384 for all mounted devices
  command: /sbin/blockdev --setra 16384 {{ item.device }}
  with_items: "{{ ansible_mounts }}"

- name: Add GreenPlum-required boot flags to the kernel (elevator=deadline transparent_hugepage=never)
  replace:
    dest: /etc/grub.conf
    regexp: '^(\s+kernel)(.*)$'
    replace: '\1\2 elevator=deadline transparent_hugepage=never'

# FIXME: add a stable reboot here
