#- name: Set GP command cache size to {{ greenplum_statement_mem }}
- name: Configure Greenplum using gpconfig
  #shell: bash -lc "gpconfig -c statement_mem -v {{ greenplum_statement_mem }}"
  shell: bash -lc "gpconfig -c {{ item.key }} -v {{ item.value }}"
  become: yes
  become_user: gpadmin
  with_dict: "{{ greenplum_config }}"
  notify:
    - Reload greenplum config

    #- name=statement_mem value={{ greenplum_statement_mem }}

#- name: Reload config
  #shell: bash -lc "pg_ctl -D {{ greenplum_datadir }}/master/gpsne-1 reload"
  #become: yes
  #become_user: "{{ greenplum_user }}"
