---
- name: Add New Relic repository
  yum:
    name: https://download.newrelic.com/pub/newrelic/el5/i386/newrelic-repo-5-3.noarch.rpm
    state: present
  
- name: Install New Relic package
  yum: 
    name: newrelic-sysmond
    state: present

- name: Set New Relic license key
  shell: nrsysmond-config --set license_key={{ new_relic_license_key }}

- name: Start New Relic System Monitor Daemon
  service:
    name: newrelic-sysmond
    state: started
