---
  - name: Create security group for Palette Insight
    ec2_group:
      name: Palette Insight
      description: Security Group allowing required access for Palette Insight machines
      state: present
      vpc_id: "{{ vpc_id }}"
      region: "{{ aws_region }}"
      rules:
        - proto: tcp
          from_port: 80
          to_port: 80
          cidr_ip: 0.0.0.0/0
        - proto: tcp
          from_port: 5432 
          to_port: 5432
          cidr_ip: 0.0.0.0/0
        - proto: tcp
          from_port: 22
          to_port: 22
          cidr_ip: 0.0.0.0/0
        - proto: tcp
          from_port: 443
          to_port: 443
          cidr_ip: 0.0.0.0/0
      rules_egress:
        - proto: all
          cidr_ip: 0.0.0.0/0
    register: ec2_group

  - name: return group id
    set_fact:
      create_security_group__group_id: "{{ ec2_group.group_id }}"
  
