---
  - name: Make sure the insight VPC subne exists
    ec2_vpc_subnet:
      vpc_id: "{{ vpc_id }}"
      cidr: 172.32.1.0/24
      state: present
      resource_tags: { Name: "Palette Insight"}
      region: "{{ aws_region }}"
    register: ec2_vpc_subnet
  
  - name: return subnet id
    set_fact:
      create_vpc_subnet__subnet_id: "{{ ec2_vpc_subnet.subnet.id }}"
