---
- name: install xfsprogs
  yum: pkg=xfsprogs state=latest

- name: format new volume
  filesystem: fstype=xfs dev={{ data_mount_dev }}

- name: edit fstab and mount the vol
  mount: name={{ data_mount_dir }} src={{ data_mount_dev }} fstype=xfs state=mounted opts="rw,noatime,inode64,allocsize=16m"

