---
# ==================== TALEND CRONTAB SCRIPTS ====================

- name: Add talend loadtables to crontab (run every minute)
  cron: user=insight name="Palette Insight Load Tables" job="{{ insight_talend_location }}/load_tables.sh"

- name: "Make sure obsolate Vacuum crontab is deleted"
  cron: user=gpadmin name="Palette Insight VACUUM" state=absent job="/home/gpadmin/vacuum.sh"

- name: Make sure obsolate Reporting crontab is deleted
  cron: user=insight name="Palette Insight Reporting" state=absent job="{{ insight_talend_location }}/run_reporting.sh"

- name: Create Load Control shell script
  template: src=loadctrl.sh dest=/home/insight/loadctrl.sh owner=insight group=insight mode="u=rwx,g=rx,o=rx"

- name: Create DB Maintenance shell script
  template: src=db_maintenance.sh dest=/home/gpadmin/db_maintenance.sh owner=gpadmin group=gpadmin mode="u=rwx,g=rx,o=rx"
  
- name: Add Load Control to crontab (every five minutes)
  cron: user=insight name="Palette Insight Load Control" minute="*/5" job="/home/insight/loadctrl.sh"
  