---
- name: Install Insight-reporting to {{ insight_reporting_location }}
  yum: name=palette-insight-reporting state=latest update_cache=yes


# ==================== INITIAL METADATA ====================

- name: Check if there is any metadata file present in the uploaded folder
  shell: >
    find /data/insight-server/uploads/{{ cluster_name }}/uploads | grep metadata
  register: metadata_already_present
  # grep: Normally the exit status is 0 if a line is selected, 1 if no lines were selected, and 2 if an error occurred.
  failed_when: metadata_already_present.rc == 2
  # we mark the task as changed if there is alrady a metadatga file here
  changed_when: metadata_already_present.rc == 1

- name: Create initial metadata directory
  file: dest=/data/insight-server/uploads/{{ cluster_name }}/uploads/_install state=directory owner=insight group=insight mode=755
  when: metadata_already_present|changed


- name: Copy initial metadata for the current tableau version for the initial loadtables
  copy:
    src: "roles/insight-loadtables/files/tableau-metadata/{{ tableau_version }}.csv.gz"
    dest: "/data/insight-server/uploads/{{ cluster_name }}/uploads/_install/metadata-install.csv.gz"
    owner: insight
    group: insight
    mode: 0644
  when: metadata_already_present|changed

# ==================== INITIAL LOADTABLES ====================

- name: Run initial loadtables to generate tables in GP
  become_user: insight
  shell: "{{ insight_talend_location }}/load_tables_nolock.sh"
  register: initial_loadtables
  failed_when: initial_loadtables|failed or '{{ loadtables_no_external_tables_error_msg }}' in initial_loadtables.stderr


# ==================== EXT ERROR TABLE  ====================

- name: Create the sql script for creating and dropping dummy_to_create_ext_error_table
  template: src=create_external_dummy_table.sql dest=/tmp/create_external_dummy_table.sql owner=gpadmin group=gpadmin

- name: Create and drop a dummy external table to create the errors table ext_error_table
  shell: >
    source {{ greenplum_install_path }}/greenplum_path.sh &&
    {{greenplum_install_path}}/bin/psql
    -d {{ insight_database_name }}
    -f /tmp/create_external_dummy_table.sql
  become: yes
  become_user: gpadmin

# ==================== FULL DATAMODEL ========================

- name: Create a copy of full_install.sql to {{ reporting_tmp_install_file }}
  copy: remote_src=yes src={{ reporting_full_install_file }} dest={{ reporting_tmp_install_file }} owner=gpadmin group=gpadmin mode="u=rw"

- name: "Replace '#schema_name#' with {{ insight_schema_name }} in {{ reporting_tmp_install_file }}"
  replace: dest={{ reporting_tmp_install_file }} regexp='#schema_name#' replace={{ insight_schema_name }}


- name: Install the full datamodel using full_install.sql
  shell: >
    source {{ greenplum_install_path }}/greenplum_path.sh &&
    {{greenplum_install_path}}/bin/psql
    -d {{ insight_database_name }}
    -f {{ reporting_tmp_install_file }}
  args:
    chdir: "{{ insight_reporting_location }}/full-install"
  register: reporting_full_install
  become: yes
  become_user: gpadmin
  ignore_errors: yes
  failed_when: "reporting_full_install.rc != 0 and ('{{ version_table_exists_error_msg }}' not in reporting_full_install.stderr)"
  changed_when: "reporting_full_install.rc == 0"

