---

# ==================== INITIAL METADATA ====================

- name: Check if there is any metadata file present in the uploaded folder
  shell: >
    find /data/insight-server/uploads/{{ cluster_name }}/uploads | grep metadata
  register: metadata_already_present
  # grep: Normally the exit status is 0 if a line is selected, 1 if no lines were selected, and 2 if an error occurred.
  failed_when: metadata_already_present.rc == 2
  # we mark the task as changed if there is alrady a metadatga file here
  changed_when: metadata_already_present.rc == 1

- name: Create initial metadata directory
  file: dest=/data/insight-server/uploads/{{ cluster_name }}/uploads/_install state=directory owner=insight group=insight mode=755
  when: metadata_already_present|changed


- name: Copy initial metadata for the current tableau version for the initial loadtables
  copy:
    src: "roles/insight-loadtables/files/tableau-metadata/{{ tableau_version }}.csv.gz"
    dest: "/data/insight-server/uploads/{{ cluster_name }}/uploads/_install/metadata-install.csv.gz"
    owner: insight
    group: insight
    mode: 0644
  when: metadata_already_present|changed

# ==================== INITIAL LOADTABLES ====================

- name: Run initial loadtables to generate tables in GP
  become_user: insight
  shell: "{{ insight_talend_location }}/load_tables.sh"
  register: initial_loadtables
  when: metadata_already_present|changed
  failed_when: initial_loadtables|failed or '{{ loadtables_no_external_tables_error_msg }}' in initial_loadtables.stderr
  # As this task may time out, do this here
  notify: Restart splunk


# ==================== EXT ERROR TABLE  ====================

- name: Create the sql script for creating and dropping dummy_to_create_ext_error_table
  template: src=create_external_dummy_table.sql dest=/tmp/create_external_dummy_table.sql owner=gpadmin group=gpadmin

- name: Create and drop a dummy external table to create the errors table ext_error_table
  shell: >
    source {{ greenplum_install_path }}/greenplum_path.sh &&
    {{greenplum_install_path}}/bin/psql
    -d {{ insight_database_name }}
    -U palette_etl_user
    -f /tmp/create_external_dummy_table.sql
  become: yes
  become_user: gpadmin

# ==================== REPORTING ========================

- name: Install Insight-reporting to {{ insight_reporting_location }}
  yum: name='{{ item }}' state=latest update_cache=yes
  with_items:
    - palette-insight-reporting
    - palette-insight-reporting-framework

- name: Install the data model
  shell: /opt/insight-toolkit/update-data-model.sh {{ insight_datamodel_version }} chdir=/opt/insight-toolkit
  environment:
    UPDATE_PROGRESS_FILE: /tmp/insight-initial-update-progress.log
  notify: Restart splunk
  register: datamodel_install_res
  changed_when: "datamodel_install_res.rc == 0 and '-------------------- OK --------------------' not in datamodel_install_res"
  become: yes
  become_user: insight
