---
- name: Install psycopg2 for ansible to modify postgres
  yum: name=python-psycopg2 state=present

- name: Install Insight-loadTables to {{ insight_talend_location }}
  yum: name=palette-insight-loadtables state=latest update_cache=yes

- name: Create directories for uploading and processing in /data/insight-server/uploads/{{ cluster_name }}
  file: path=/data/insight-server/uploads/{{ cluster_name }}{{ item }} state=directory mode=0755 owner=insight group=insight
  with_items:
    - ""
    - /processing
    - /uploads


- include: "database-setup.yml"
- include: "insight-gpfdist.yml"
- include: "talend-jobs.yml"
- include: "install-reporting.yml"
- include: "crontab-tasks.yml"

- name: Create the temporary crontab / status storage directory for insight-services
  file: path={{ insight_services_data_dir }} state=directory mode=0755 owner=root group=root

- name: Create the insight-services shell script to gracefully stop and start greenplum and related components
  template: src=insight-services.sh dest=/usr/local/bin/insight-services owner=root group=root mode=0755

