---
- name: Install psycopg2 for ansible to momdify postgres
  yum: name=python-psycopg2 state=present

- name: Install Insight-loadTables to {{ insight_talend_location }}
  yum: name=palette-insight-loadtables state=latest update_cache=yes

- name: Create directories for uploading and processing in /data/insight-server/uploads/{{ cluster_name }}
  file: path=/data/insight-server/uploads/{{ cluster_name }}{{ item }} state=directory mode=0755 owner=insight group=insight
  with_items:
    - ""
    - /processing


- include: "database-setup.yml"
- include: "insight-gpfdist.yml"
- include: "talend-jobs.yml"

#- name: Add palette users to GP
  #debug: msg=""
#- name: Create palette schema in GP
  #debug: msg=""
#- name: Start GPFDist
  #debug: msg=""

- name: Run initial loadtables to generate tables in GP
  become_user: insight
  shell: "{{ insight_talend_location }}/load_tables.sh"
  when: false

- name: Run the creation SQL
  debug: msg=""
  when: false



- name: Add talend loadtables to crontab (run every minute)
  cron: user=insight name="Palette Insight Load Tables" job="{{ insight_talend_location }}/load_tables.sh"
  when: false

#- name: Run fullinstall.sql
  #shell: "psql

#- name: Add reporting to crontab (every five minutes)
  #cron: user=insight name="Palette Insight Load Tables" minute="5-55/5" job="{{ insight_talend_location }}/load_tables.sh"


