---
- name: Create the Talend loadtables runner script
  template: src=load_tables_runner.sh dest={{ insight_talend_location }}/load_tables_runner.sh owner=insight group=insight mode=755

- name: Create the Talend config.xml in /data/insight-server/uploads/{{ cluster_name }}
  template: src=config.xml dest=/data/insight-server/uploads/{{ cluster_name }}/config.xml owner=insight group=insight mode=640

- name: Create the log directory for talend components
  file: path={{ talend_log_path }} state=directory mode=0775 owner=root group=insight


- name: Create log4j.xml for Talend LoadTables
  template: src=loadtables.log4j.xml dest={{ insight_talend_location }}/Palette_Insight_Init_ImportTable/log4j.xml mode=644

- name: Create log4j.xml for Talend Reporting
  template: src=reporting.log4j.xml dest={{ insight_talend_location }}/Palette_Insight_Init_Reporting/log4j.xml mode=644

- name: Create the talend runner scripts
  template: src={{ item }} dest={{ insight_talend_location }}/{{ item }} owner=insight group=insight mode=755
  with_items:
    - load_tables.sh
    - load_tables_nolock.sh
    - run_reporting.sh

#- name: Create the load_tables.sh script
  #template: src=load_tables.sh dest={{ insight_talend_location }}/load_tables.sh owner=insight group=insight mode=755

#- name: Create the load_tables.sh script
  #template: src=load_tables.sh dest={{ insight_talend_location }}/load_tables.sh owner=insight group=insight mode=755

#- name: Create the run_reporting.sh script
  #template: src=run_reporting.sh dest={{ insight_talend_location }}/run_reporting.sh owner=insight group=insight mode=755

