---
- name: Install Insight Server
  shell: /opt/insight-toolkit/update-insight-server.sh
  environment:
    UPDATE_PROGRESS_FILE: /tmp/insight-initial-update-progress.log
  become: yes
  become_user: insight
  notify:
    - Restart splunk
    - Restart nginx
