---

- name: Add the NGINX repository definition
  template: src=nginx.repo dest=/etc/yum.repos.d/nginx.repo

- name: Create the GPG key for NGINX
  copy: src=RPM-GPG-KEY-NGINX dest=/etc/pki/rpm-gpg

- name: Install nginx
  yum: name=nginx state=present

- name: Configure SELinux to allow httpd network connect
  seboolean: name=httpd_can_network_connect state=yes persistent=yes


# FIREWALLD IS ONLY FOR CENTOS & RH > 7
#- name: insert firewalld rule for nginx
#  firewalld: port={{ nginx_port }}/tcp permanent=true state=enabled immediate=yes

- name: http service state
  service: name=nginx state=started enabled=yes
