---
- name: Install DataDog Agent
  hosts: center
  remote_user: ubuntu
  become: yes
  become_user: root

  tasks:
    - include_vars: roles/datadog-agent/vars/main.yml

    - name: Download and install DataDog Agent
      shell: 'DD_API_KEY={{ datadog_api_key }} bash -c "$(curl -L https://raw.githubusercontent.com/DataDog/dd-agent/master/packaging/datadog-agent/source/install_agent.sh)"'
