---
- hosts: localhost
  gather_facts: False
  connection: local
  user: remote

  vars_prompt:
    - name: "AWS_ACCESS_KEY"
      prompt: "Enter AWS Access key"
      private: yes 
    - name: "AWS_SECRET_KEY"
      prompt: "Enter AWS Secret Key"
      private: yes
    - name: "CUSTOMER_NAME"
      prompt: "Enter customer name/ticker"
      private: no

  environment:
    AWS_ACCESS_KEY: "{{ AWS_ACCESS_KEY }}"
    AWS_SECRET_KEY: "{{ AWS_SECRET_KEY }}"

  roles:
      - ec2-provision
