---
- name: Ensure centos user
  hosts: insight-server
  remote_user: root
  become: yes
  become_user: root

  roles:
    - centos-user

  tasks:
    - name: Place your SSH key to authorized keys of centos user
      authorized_key:
        user: centos
        # Make it accessible via Palette-Insight-Standard-Keypair-2016-01-19.pem (you can find it in 1password)
        key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCiWYolmK1PdAvsevdg4SO3CAbQ8x8CAjstp5mYkEYEhAh+sFVvJxmLTYJYzMMIeFWm+SVcr+rfCnioxZ5rVHNKmRjqAGNPvSeqEenmlh08uwSggJQkJw95N+N4vfrEhshVfEVMn7TLizfD0Jkvv+Y5YFNlfCD0r8nyjBoL8iEBgsSesgrNoAL7Lg2kOLRpyREBfyI6nkS4pLQVr2J9aP9VGbGJkZsVRge9sVO1qY8dAA0TGWgMtqOe5eAJZgNC+EA5PfORk8fytp597Nwyh6eHkhgLN6k6/fTkxggx8tcJOAZ9e9D5SRGNEr5H+ofpTtOfgKfw3cEcXJVQWTQ9OWZZ Palette-Insight-Standard-Keypair-2016-01-19"
