---
- name: First time setup & install of a Palette Insight Server machine
  hosts: insight-server
  remote_user: "{{ uservar }}"
  become: yes
  become_user: root

  roles:
    - common
    - xfs-init
    - palette-dev-tools
    - nginx
    - supervisor
    - splunkforwarder
    - golang
    - greenplum
    - greenplum-data
    - insight-server
    - insight-loadtables

