---
- name: Provision Palette Insight-server VM image
  hosts: all
  remote_user: root
  roles:
    - common
    #- xfs-init
    - tmpfs
    - palette-dev-tools
    - nginx
    - supervisor
    - splunkforwarder
    - golang
    - greenplum
    - greenplum-data
    - insight-server
    #- insight-loadtables
    - insight-services-webui
    #- sanity-check
  vars:
    packer: true
