---
- name: Setup sanity checks on database
  hosts: insight-server
  remote_user: centos
  become: yes
  become_user: centos

  tasks:
    - name: Create temp directory for github-release-downloader
      file: path=/tmp/dl-github-release state=directory mode=0775

    # Unfortunately download fails this way...
    # - name: Download github release downloader
    #   unarchive: src="https://github.com/palette-software/dl-github-release/releases/download/v1.0.2/linux_amd64.zip" dest=/tmp/dl-github-release copy=no

    - name: Download github release downloader
      shell: 'wget -P /tmp/dl-github-release/ https://github.com/palette-software/dl-github-release/releases/download/v1.0.2/linux_amd64.zip'

    - name: Unpack github release downloader
      unarchive: src="/tmp/dl-github-release/linux_amd64.zip" dest=/tmp/dl-github-release copy=no

    - name: Download insight-tester with github release downloader
      shell: '/tmp/dl-github-release/linux_amd64/dl-github-release palette-software insight-tester {{ github_token }}'
      args:
        chdir: /tmp/dl-github-release/linux_amd64
      no_log: True

    - name: Create directory for insight-tester which contains the dbcheck
      file: path='/home/centos/insight-tester/' state=directory mode=0775

    - name: Unpack insight-tester to acquire dbcheck (sanity checker)
      unarchive: src=/tmp/dl-github-release/linux_amd64/linux_amd64.zip dest=/home/centos/insight-tester copy=no

    - name: Delete temporary folders
      file: path='/tmp/dl-github-release' state=absent

    - name: Make sanity check configuration inplace
      template: src=roles/sanity-check/templates/Config.yml dest=/home/centos/insight-tester/linux_amd64/sanity_check/Config.yml owner=centos group=centos

    # - name: Execute sanity check once
    #   shell: './dbcheck tests/sanity_checks.yml Config.yml'
    #   args:
    #     chdir: /home/centos/insight-tester/linux_amd64/sanity_check

    - name: Schedule sanity check via cron
      cron: name="Run DB sanity check" minute="*/5" job="/home/centos/insight-tester/linux_amd64/sanity_check/dbcheck /home/centos/insight-tester/linux_amd64/sanity_check/tests/sanity_checks.yml /home/centos/insight-tester/linux_amd64/sanity_check/Config.yml" user=centos
      become_user: root
