---
- name: Install Palette Dev Team tools
  yum: name=git,curl,wget,screen,tmux,htop,mosh state=present

- name: Install OpenJDK (1.8)
  yum: name=java-1.8.0-openjdk state=present

- include: 'vim.yml'
