---
- name: Install Palette Dev Team tools
  yum: name={{ item }} state=present
  with_items:
    - git
    - curl
    - wget
    - screen
    - tmux
    - htop

- name: Install OpenJDK (1.8)
  yum: name=java-1.8.0-openjdk state=present

- include: 'vim.yml'
