# ==================== INIT SCRIPT ====================

- name: Copy the init.d script for GreenPlum
  template: src=init.d/greenplum dest=/etc/init.d/greenplum owner=root group=root mode=0755

- name: Updating chkconfig for GreenPlum
  shell: chkconfig --add greenplum

- name: Create /var/log directory for greenplum logs
  file: path=/var/log/greenplum owner=root group=gpadmin state=directory mode="u=rwx,g=rwx,o="

- name: Greenplum service start & enable on restart
  service: name=greenplum state=started enabled=yes

