---

- name: Check if GreenPlum data directory exists
  stat: path={{ greenplum_datadir }}/master/gpsne-1
  register: gp_master_dir

- name: Run GpInitSystem if the GreenPlum data directory does not exist
  include: "gpinitsystem.yml"
  when: not gp_master_dir.stat.exists

- name: Greenplum as init.d service
  include: "greenplum-initscript.yml"

- name: Enable SSL for Greenplum
  include: "greenplum-ssl.yml"

- name: Allow remote logins
  lineinfile: dest={{ greenplum_datadir }}/master/gpsne-1/pg_hba.conf line={{ item }}
  with_items:
    - "local all all trust"
    - "host all all 0.0.0.0/0 md5"
    # allow ssl connection
    - "hostssl all all 0.0.0.0/0 md5"
    - "host all all ::1/128 trust"

- name: Tune Greenplum before the restart
  include: "tuning.yml"

